name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3
        with:
          activate-environment: snowsar-ci
          auto-activate-base: false
          environment-file: environment-ci.yml
          use-mamba: true

      - name: Install package
        run: conda run -n snowsar-ci python -m pip install --no-deps .

      - name: Run tests
        run: conda run -n snowsar-ci pytest -q
